### ISSUE TITLE
__init__.py is empty

### ISSUE THREAD

**Issue by theunsolvedenigma** [parklez/twitch-bot#34]
![image](https://user-images.githubusercontent.com/67552140/132962388-ca243d0b-7892-465d-a5cd-682ce7ef99b4.png)

Had errors when attempting to run the bot as it could not find module "Parky_Bot". Pretty sure this isn't supposed to be empty?

This is the same with all the init files in the parky_bot package.

**Comment by parklez** [comment]
Hi, Github didn't notify me about your post...

The intended way to run the application is by calling it like a module:
```sh
python -m parky_bot.app
```
If you so wish to run it directly, move `app.py` to its parent folder. Doing so will allow you to run it by double clicking.

**Comment by theunsolvedenigma** [comment]
Ah, my bad on the init files xD

However calling it like a package from terminal:
![image](https://user-images.githubusercontent.com/67552140/133560536-a68f5ea5-bc23-4d38-9348-bae0d1128b2e.png)
tested this on my Pi with the same issue..

**Comment by parklez** [comment]
> Ah, my bad on the init files xD
> 
> However calling it like a package from terminal:
> ![image](https://user-images.githubusercontent.com/67552140/133560536-a68f5ea5-bc23-4d38-9348-bae0d1128b2e.png)
> tested this on my Pi with the same issue..

From the looks of your previous screenshot, you're supposed to run that command on the `twitch-bot-1.0.2` directory.
navigate there using `cd twitch-bot-1.0.2`. Best of luck!
